@startuml
class ParticipantDto {
    + Id : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + UserId : string <<get>> <<set>>
    + Points : int <<get>> <<set>>
    + TournamentId : string <<get>> <<set>>
    + Status : ParticipantStatus <<get>> <<set>>
}
@enduml
