@startuml
class NewsDto {
    + Id : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Content : string <<get>> <<set>>
    + PublishingDate : DateTime <<get>> <<set>>
    + CategoryId : string <<get>> <<set>>
    + AuthorId : string <<get>> <<set>>
    + tags : List<TagDto> <<get>> <<set>>
}
@enduml
