@startuml
class NewsDto {
    + Id : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Content : string <<get>> <<set>>
    + PublishingDate : DateTime <<get>> <<set>>
    + CategoryId : string <<get>> <<set>>
    + AuthorId : string <<get>> <<set>>
    + tags : List<TagDto> <<get>> <<set>>
}
class NewsCleanDto {
    + Id : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + PublishingDate : DateTime <<get>> <<set>>
    + AuthorId : string <<get>> <<set>>
}
class TagDto {
    + Id : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
}
class NewsFilter {
    + SearchString : string <<get>> <<set>>
    + Tags : List<TagDto> <<get>> <<set>>
    + CategoryId : string <<get>> <<set>>
}
@enduml
