@startuml
class Participant {
    + Participant()
    + Id : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + TournamentId : string <<get>> <<set>>
    + Points : int <<get>> <<set>>
    + Status : ParticipantStatus <<get>> <<set>>
    + Tournament : Tournament <<get>> <<set>>
}
@enduml
