@startuml
class MatchDto {
    + Id : string <<get>> <<set>>
    + Round : int <<get>> <<set>>
    + StartTime : DateTime <<get>> <<set>>
    + Status : MatchStatus <<get>> <<set>>
    + MatchOrder : int <<get>> <<set>>
    + WinScore : int <<get>> <<set>>
    + LooseScore : int <<get>> <<set>>
    + EndTime : DateTime <<get>> <<set>>
    + CategoryId : string <<get>> <<set>>
    + WinnerId : string <<get>> <<set>>
    + Participant1Id : string <<get>> <<set>>
    + Participant2Id : string <<get>> <<set>>
    + TournamentId : string <<get>> <<set>>
    + NextMatchId : string? <<get>> <<set>>
    + OwnerId : string <<get>> <<set>>
}
@enduml
