@startuml
interface IParticipantRepository {
    GetByIdAsync(id:string) : Task<Participant>
    GetAsync(tournamentId:string, page:int, pageSize:int) : Task<List<Participant>>
    + GetAllAsync(tournamentId:string) : Task<List<Participant>>
    AddAsync(participant:Participant) : Task<Participant>
    DeleteAsync(participant:Participant) : Task<Participant>
    UpdateAsync(participant:Participant) : Task<Participant>
    + AddParticipantToTournament(tournamentId:string, participantId:string) : Task<Participant>
    + RemoveParticipantFromTournament(tournamentId:string, participantId:string) : Task<Participant>
}
@enduml
