version: '3.9'

services:
  # User Service
  user-service:
    build:
      context: ./UserService
    ports:
      - "5153:5153"
    environment:
      - ASPNETCORE_URLS=http://+:5153
      - ConnectionStrings__DataBase=Host=user-db;Port=5432;Database=userdb;Username=postgres;Password=postgres
    depends_on:
      - user-db
    networks:
      - backend

  user-db:
    image: postgres:16
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - backend

  # Tournament Service
  tournament-service:
    build:
      context: ./TournamentService
    ports:
      - "5276:5276"
    environment:
      - ASPNETCORE_URLS=http://+:5276
      - ConnectionStrings__DataBase=Host=tournament-db;Port=5432;Database=tournamentdb;Username=postgres;Password=postgres
      - grpcSettings__Address=http://match-service:5000
    depends_on:
      - tournament-db
      - match-service
    networks:
      - backend

  tournament-db:
    image: postgres:16
    environment:
      POSTGRES_DB: tournamentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - tournament-db-data:/var/lib/postgresql/data
    networks:
      - backend

  # Match Service
  match-service:
    build:
      context: ./MatchService
    ports:
      - "5083:5083"
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5083;http://+:5000
      - ConnectionStrings__DataBase=Host=match-db;Port=5432;Database=matchdb;Username=postgres;Password=postgres
    depends_on:
      - match-db
    networks:
      - backend

  match-db:
    image: postgres:16
    environment:
      POSTGRES_DB: matchdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - match-db-data:/var/lib/postgresql/data
    networks:
      - backend

  # News Service
  news-service:
    build:
      context: ./NewsService
    ports:
      - "5149:5149"
    environment:
      - ASPNETCORE_URLS=http://+:5149
      - ConnectionStrings__DataBase=Host=news-db;Port=5432;Database=newsdb;Username=postgres;Password=postgres
    depends_on:
      - news-db
    networks:
      - backend

  news-db:
    image: postgres:16
    environment:
      POSTGRES_DB: newsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - news-db-data:/var/lib/postgresql/data
    networks:
      - backend

  # Discipline Service
  discipline-service:
    build:
      context: ./DisciplineService
    ports:
      - "5215:5215"
    environment:
      - ASPNETCORE_URLS=http://+:5215
      - ConnectionStrings__DataBase=Host=discipline-db;Port=5432;Database=disciplinedb;Username=postgres;Password=postgres
    depends_on:
      - discipline-db
    networks:
      - backend

  discipline-db:
    image: postgres:16
    environment:
      POSTGRES_DB: disciplinedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - discipline-db-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  user-db-data:
  tournament-db-data:
  match-db-data:
  news-db-data:
  discipline-db-data:
