@startuml
class ParticipantController {
    - <<readonly>> _participantService : IParticipantService
    + ParticipantController(participantService:IParticipantService)
    + <<async>> GetParticipantsAsync(tournamentId:string, page:int, pageSize:int) : Task<IActionResult>
    + <<async>> UpdateParticipantAsync(id:string, dto:ParticipantDto) : Task<IActionResult>
    + <<async>> DeleteParticipantAsync(Id:string) : Task<IActionResult>
    + <<async>> AddParticipantAsync(tournamentId:string, dto:ParticipantDto) : Task<IActionResult>
    + <<async>> GetByIdAsync(id:string) : Task<IActionResult>
}
ControllerBase <|-- ParticipantController
@enduml
